# Generated by Django 5.2.3 on 2025-06-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_date_of_birth_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="is staff"),
        ),
    ]
