# Generated by Django 5.2.3 on 2025-07-22 09:55

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_country_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
