# Generated by Django 5.2.3 on 2025-07-22 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Level title (e.g. 'Beginner', 'Intermediate')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief overview of what this level covers",
                        null=True,
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        help_text="Order position (1-based index)", unique=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this level publicly accessible?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Level",
                "verbose_name_plural": "Course Levels",
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Lesson title", max_length=100)),
                (
                    "content",
                    models.TextField(
                        help_text="Main content (HTML/text or file reference)"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated completion time (minutes)",
                        null=True,
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        help_text="Order within level (1-based index)"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Content"),
                            ("video", "Video Lesson"),
                            ("quiz", "Interactive Quiz"),
                        ],
                        default="text",
                        help_text="Type of lesson content",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.ForeignKey(
                        help_text="Parent level for this lesson",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="core.level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Lesson",
                "verbose_name_plural": "Course Lessons",
                "ordering": ["level__order_index", "order_index"],
                "unique_together": {("level", "order_index")},
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                ("bookmarked", models.BooleanField(default=False)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.lesson"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Progress Records",
                "unique_together": {("user", "lesson")},
            },
        ),
    ]
