# Generated by Django 5.2.3 on 2025-07-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_level_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
