# Generated by Django 5.2.3 on 2025-07-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_lesson_video_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="unlock_threshold",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Minimum completed lessons from previous level to unlock",
            ),
        ),
    ]
