# Generated by Django 5.2.3 on 2025-07-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_level_unlock_threshold"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="video_link",
            new_name="video",
        ),
    ]
